### ISSUE TITLE
Empty Dictionary when reading from Csv

### ISSUE THREAD

**Issue by rana-ayman** [BadMonkeysTeam/MandrillPrimer#1]
![MandrillPrimer_ barchart](https://user-images.githubusercontent.com/52454742/69743478-6a724000-1136-11ea-84ee-5e336d3fba48.JPG)
Hello, 

Thank you for the amazing package. 
I tried it, it worked when data are imported manually using code block to import chart data, but it couldn't work with reading from CSV file. 

I attached the script. 
and the excel cvs data file. 
![Capture 1](https://user-images.githubusercontent.com/52454742/69743721-d3f24e80-1136-11ea-8845-bbce2a668d7e.JPG). 

Thanks for your help in advance.

Rana

**Comment by ksobon** [comment]
@rana-ayman Please make sure that you have the latest version of Mandrill package installed. Here's how I am able to create a bar chart from excel data similar to yours: 

![image](https://user-images.githubusercontent.com/529781/69886150-9c0e1700-12ae-11ea-8768-b27f643b7f26.png)

Data: 

![image](https://user-images.githubusercontent.com/529781/69886161-a5977f00-12ae-11ea-9176-5bd35d8030b3.png)

Since you haven't posted any sample files (excel, dynamo), I can't tell you what your issue is. Please post some files and i will be happy to help.

**Comment by rana-ayman** [comment]
@ksobon Thank you very much for your prompt reply. 

![LCA bar chart visualization](https://user-images.githubusercontent.com/52454742/70091043-3b1a7200-1613-11ea-885a-546409c5332d.JPG)

I downloaded the latest Mandrill package, but still I tried to test the script and still it is not working. 

Thank you for your help. 

Rana

**Comment by rana-ayman** [comment]
> @ksobon Thank you very much for your prompt reply.
> 
> ![LCA bar chart visualization](https://user-images.githubusercontent.com/52454742/70091043-3b1a7200-1613-11ea-885a-546409c5332d.JPG)
> Find attached the tested script and photo for the Run.
> 
> I downloaded the latest Mandrill package, but still I tried to test the script and still it is not working.
> 
> Thank you for your help.
> 
> Rana
> 
> [LCA_Representation_02.zip](https://github.com/BadMonkeysTeam/MandrillPrimer/files/3918780/LCA_Representation_02.zip)

#needhelp

**Comment by rana-ayman** [comment]
Resolved. 
It is working. 

Rana
